env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[!6a5062f2fab1c137140c1134d64d384b624e152a6b6351577a7d34a5d98d0ca1a0d290063da11a6fc38da98e9e210c0d!]"
  TG_TOKEN: "ENCRYPTED[!0c1d90d24b217464a44b9e48b501ca8eb3f170e4adee80f275e2c7a30a8f8aabff972da248c094552440b1a0cb358540!]"
  TG_CHAT_ID: "ENCRYPTED[!a3fbdb4e673a1e6f8ffcf72ffa11fe28ce19226b06c406bbb83d0756cbffd4c3855315719209da8492b91db84f412b1c!]"
  WORKDIR: "/tmp"
  EMAIL: "ENCRYPTED[!84f0eafd3dc15782842e25fd97ae436194a910a21465f4f5a7622f351d0b64d9fb0dcbf1b7b6ba411c737357e4fd431d!]"
  CIRRUS_CLONE_DEPTH: "1"
  credentials: "ENCRYPTED[!9c169f4a5dc4363700addcb64e823ddf9bac3b781dc42dd240d4f78ee300fdda8f44c1f11356699b129ba33e1982b210!]"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'travarilo'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - git config --global user.name "Rizky Benggolo"
     - git config --global user.email "travarilo@gmail.com"
     - echo "$credentials" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
